---
deployment:
  tasks:
    - export PROJECT=/home3/recruiting/jobs.ihre-stelle.de/laravel/ihre-stelle
    - cd $PROJECT
    - /opt/cpanel/composer/bin/composer install --no-dev --optimize-autoloader
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache
    - php artisan migrate --force
    - php artisan storage:link