---
deployment:
  tasks:
    - cd ihre-stelle
    - /opt/cpanel/composer/bin/composer install --no-dev --optimize-autoloader
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache
    - php artisan migrate --force
    - php artisan storage:link
